# fly.toml app configuration file generated for opo-finder on 2024-07-15T17:30:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opo-finder'
primary_region = 'mad'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
